USE sHastane

CREATE TABLE tblRandevular
(
ID INT IDENTITY(1,1) NOT NULL,
BOLUMID INT NOT NULL,
DOKTORLARID INT NOT NULL,
HASTAID INT NOT NULL,
TARÝH DATE NOT NULL,
SAAT TIME NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(BOLUMID) REFERENCES tblBolumler(ID),
FOREIGN KEY (DOKTORLARID) REFERENCES tblDoktorlar(ID),
FOREIGN KEY(HASTAID) REFERENCES tblHastalar(ID)
)
