USE sHastane

CREATE TABLE tblgecicirandevular(

ID INT IDENTITY(1,1) NOT NULL,
BOLUMID INT NOT NULL,
DOKTORLARID INT NOT NULL,
HASTAID INT NOT NULL,
TARÝH VARCHAR(MAX) NOT NULL,
SAAT VARCHAR(MAX) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(BOLUMID) REFERENCES tblBolumler(ID),
FOREIGN KEY(DOKTORLARID) REFERENCES tblDoktorlar(ID),
FOREIGN KEY(HASTAID) REFERENCES tblHastalar(ID)
)